name: Deploy notebook to Cloud Run
on:
  workflow_dispatch:

env:
  PROJECT_ID: "hack-team-hack-o-holics"
  REGION: "us-central1"
  RUN_SERVICE: "hack-o-holics-notebook"
  BASE_AR_URL: "us-central1-docker.pkg.dev"
  AR_NAME: "hack-o-holic"
  IMAGE_NAME: "hack-o-holics-notebook"

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Authenticate to GCP as Infrastructure SA for deployment'
        uses: 'google-github-actions/auth@v1'
        with:
          export_environment_variables: true
          project_id : ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.INFRA_SA_EMAIL }} # Use your Infrastructure SA to manage resources

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Docker login
        run: gcloud auth configure-docker ${{ env.BASE_AR_URL }}

      - name: Image tag
        id: tag
        run: |
          echo "tag=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build notebook/. -f notebook/Dockerfile -t ${{ env.BASE_AR_URL }}/${{ env.PROJECT_ID }}/${{ env.AR_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        
      - name: Push image to Artifact Registery
        run: docker push ${{ env.BASE_AR_URL }}/${{ env.PROJECT_ID }}/${{ env.AR_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}  #us.gcr.io/hack-team-hack-o-holics/hack-o-holics-ui:${{ steps.tag.outputs.tag }}
        
#      - name: Deploy to CloudRun
#        run : gcloud run deploy ${{ env.RUN_SERVICE }} --image=${{ env.BASE_AR_URL }}/${{ env.PROJECT_ID }}/${{ env.AR_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }}
