name: Deploy Cloud Run using the deploy-cloudrun GitHub Action
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Authenticate to GCP as Infrastructure SA for deployment'
        uses: 'google-github-actions/auth@v1'
        with:
          export_environment_variables: true
          project_id : ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.INFRA_SA_EMAIL }} # Use your Infrastructure SA to manage resources

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Docker login
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Image tag
        id: tag
        run: |
          echo "tag=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build . -f Dockerfile -t us-central1-docker.pkg.dev/hack-team-hack-o-holics/hack-o-holic/hack-o-holics-ui:${{ steps.tag.outputs.tag }}
        
      - name: Push image to GCR
        run: docker push us-central1-docker.pkg.dev/hack-team-hack-o-holics/hack-o-holic/hack-o-holics-ui:${{ steps.tag.outputs.tag }}  #us.gcr.io/hack-team-hack-o-holics/hack-o-holics-ui:${{ steps.tag.outputs.tag }}

