name: Example - Using gcloud
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          export_environment_variables: true
          project_id : ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.INFRA_SA_EMAIL }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Create storage bucket'
        run: 'gcloud storage buckets create "gs://${{ vars.PROJECT_ID }}_github_bucket" --location=EU --uniform-bucket-level-access --public-access-prevention'